### ISSUE TITLE
ItemQualities errors on paper-1.19.2, doesn't load or work.

### ISSUE THREAD

**Issue by twistedfatez** [Steel-Dev/ItemQualities#22]
[23:45:25 ERROR]: [org.bukkit.craftbukkit.v1_19_R1.CraftServer] This version of Minecraft is unsupported: 1.19.2 initializing ItemQualities v1.1.0 (Is it up to date?)
dev.jorel.commandapi.exceptions.UnsupportedVersionException: This version of Minecraft is unsupported: 1.19.2
	at dev.jorel.commandapi.CommandAPIVersionHandler.getNMS(CommandAPIVersionHandler.java:86) ~[ItemQualities-1.1.0.jar:?]
	at dev.jorel.commandapi.CommandAPIHandler.<init>(CommandAPIHandler.java:155) ~[ItemQualities-1.1.0.jar:?]
	at dev.jorel.commandapi.CommandAPIHandler.getInstance(CommandAPIHandler.java:140) ~[ItemQualities-1.1.0.jar:?]
	at dev.jorel.commandapi.CommandAPI.onLoad(CommandAPI.java:166) ~[ItemQualities-1.1.0.jar:?]
	at com.abraxas.itemqualities.ItemQualities.onLoad(ItemQualities.java:40) ~[ItemQualities-1.1.0.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:429) ~[paper-1.19.2.jar:git-Paper-191]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:278) ~[paper-1.19.2.jar:git-Paper-191]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-191]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-191]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by jumperdenfer** [comment]
Sadly this plugin use a specific version of Dev.Joral.CommandAPI, you has the choice to w8 until the current dev resolve this, or... you can take the source, change the "dev.joral" to the last version in pom.xml and rebuild. IDK if the owner of this plugin allow this  method
